apiVersion: v1
kind: Service
metadata:
  name: dic-backend-service
  namespace: dictionary-namespace
spec:
  selector:
    app: dic-backend
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088